services:

  db:
    image: postgres:15
    container_name: face_recognition_db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: django1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emer123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

  web:
    build:
      context: ./back_re_facial
      dockerfile: Dockerfile
    container_name: face_recognition_web

    ports:
      - "8000:8000"

    depends_on:
      - db
    networks:
      - app-network

    volumes:
      - ./back_re_facial:/app


  db_websocket:
      image: postgres:15
      container_name: db_micro_con
      ports:
        - "5436:5432"
      environment:
        - POSTGRES_DB=micro
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      networks:
        - app-network




volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
