version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db_micro_con
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=micro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network

  backend:
    build: 
      context: ./websocket
      dockerfile: Dockerfile
    container_name: micro_container
    ports:
      - "8000:3000"

    environment:
      - POSTGRES_HOST=db            # <--- La juega: usar el nombre del servicio
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=micro
      - POSTGRES_SSL=false
      - PORT=3000
      - DB_TYPE=postgres

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

    depends_on:
      - db

    networks:
      - app-network
  
  redis:
    image: redis
    container_name: redis_db_micro
    ports: 
      - "6378:6379"
    networks:
      - app-network 

networks:
  app-network: