# Generated by Django 5.1.4 on 2025-01-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_edad_user_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_registro',
            field=models.ImageField(blank=True, null=True, upload_to='user/registro'),
        ),
    ]
