# Generated by Django 5.1.4 on 2025-01-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_imagen_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fk_rol',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
