# Generated by Django 5.1.4 on 2025-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_fk_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fk_rol',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
